### PR TITLE
Database Performance Audit

### PR DESCRIPTION
**Pull request by lucabenaventew**
# Project Updates :green_circle: 
- [ ] Use EXPLAIN ANALYZE on the following queries:
- [ ] explain analyze SELECT COUNT(*) FROM visits where animal_id = 4;
- [ ] explain analyze SELECT * FROM visits where vet_id = 2;
- [ ] explain analyze SELECT * FROM owners where email = 'owner_18327@mail.com';
- [ ] Improve execution time on queries (less than 1000 ms)
## Made by Ghislain and Luca
# BEFORE
before1
before2
before3

# AFTER
evidence3
All the requirements have been completed

### CODE REVIEW

**Review by mukhammadrizooff — CHANGES_REQUESTED** [review]
Hi @TEAM, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!



## Highlights
- Clean code ✔️ 
- Good implementations ✔️ 
- Descriptive Commit history ✔️ 

## Required Changes ♻️
- [ ] [REQUIRED] Good job so far 👍 I appreciate what you did, but you should have put `2 different screenshots` in this milestone's `Pull Request` description, they are:

- 1-The first screenshot should show how much time the query takes `BEFORE` the improvements introduced.
- 2-The second screenshot should show how much time the query takes `AFTER` the improvements introduced.

image

- [ ] [REQUIRED] Good job so far! Please you should do this milestone with your `coding partner` but I don't see the any `commit` your partner has made 😃 

image

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by lucabenaventew** [comment]
# BEFORE
before1
before2
before3

# AFTER
evidence3
All the requirements have been completed

The project was done in a zoom meeting. what is my friend supposed to commit? all the requirements have been completed

**Review by sja-thedude — CHANGES_REQUESTED** [review]
## Required Changes ♻️

Hi @lucabenaventew, This is @sja-thedude your code reviewer.

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

200w

 ## Highlights
✔️ Good job so far

 ## Required Changes ♻️
- [ ] Kindly make sure that the before query execution time should be around 1000ms. 
- [ ] As suggested by the previous reviewer, kindly make sure you have commits from both the partners in your pair programming group.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me [@sja-thedude] in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by lucabenaventew** [comment]
Hello @sja-thedude the thing is that we added to many new data into the table since it was running so fast so we had to repeat step 5 some more times... It was using around 2.500ms and after creating the Indexes it went as it shows in the picture. kindly accept our project, thank you.

**Comment by lucabenaventew** [comment]
# BEFORE
a
b
c


# AFTER
evidence3
All the requirements have been completed

**Review by omar-muhamad — APPROVED** [review]
# Approved ✔
### Hi @lucabenaventew and @GhislainMitahi,

Great job, Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

thumbs-up-agree


## (Highlights) Good Points: :+1:
- You documented your work professionally. ✔
- You used the correct workflow.  ✔
- All linters checks are ok. ✔

## (Changes Required) Aspects to improve: ♻️

- N/A

## [Optional] suggestions:

- N/A

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

**Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear, and please remember to tag me in your question so I can receive the notification**

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

**Pull request merged**
